match: point_line+              
                                   
point_line: PLAYER ":" OUTCOME SHOT? LOCATION?   

PLAYER:  "P1" | "P2"
OUTCOME: "ACE" | "DF" | "WINNER" | "ERROR"
SHOT:    "FH" | "BH" | "VOLLEY" | "SMASH"
LOCATION:"T"  | "WIDE" | "CC" | "DL"


%import common.WS_INLINE
%ignore WS_INLINE           
%ignore /[\r\n]+/           
